default_platform(:android)

platform :android do
  desc "Create a production android build"
  lane :build_production do

    # Since Fastlane is inside the `android/fastlane` folder you have to go navigate to the root folder
    Dir.chdir("../..") do
      # This line creates the android build
      sh "flutter build appbundle --target \"lib/main_production.dart\" --flavor \"production\" --release"
    end

    # This line verifies that you created the file
    if File.exist?(File.dirname(__FILE__) + "./../build/app/outputs/bundle/productionRelease/app-production-release.aab")
      UI.message('Found apk or aab file')
    else
      UI.message('Unable to find apk or aab')
    end
  end

  desc "upload the created android build to Play Store"
  lane :deploy_prod do
    AAB_PATH = "./../build/app/outputs/bundle/productionRelease/app-production-release.aab"
    
    validate_play_store_json_key(
      json_key: ENV['PLAYSTORE_JSON_PATH'] || "../store_certificates/playstore.json",
    )
    
    upload_to_play_store(
      track: "internal",
      rollout: "1",
      json_key: ENV['PLAYSTORE_JSON_PATH'] || "../store_certificates/playstore.json",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      aab: AAB_PATH
    )


    firebase_app_distribution(
      app: "1:1234567890:ios:0a1b2c3d4e5f67890"
    )
  end
end
